// <auto-generated />
namespace ProjetoCondominio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OtherEntities1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OtherEntities1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003161910428_OtherEntities1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
